name: service_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - name: Install dependencies
        run: |
          go version &&
          go mod tidy &&
          go install github.com/onsi/ginkgo/v2/ginkgo &&
          go get github.com/onsi/gomega/...
      - name: Run Test
        run: ginkgo -r -v --trace --coverprofile=.cover-report.out ./...
